### PR TITLE
Remove space at the beginning of update price url

### PR DESCRIPTION
**Pull request by derron**
There is a space at the beginning of update price url, it will cause an error while making http request.

### CODE REVIEW

**Comment by area** [comment]
I'm seeing this too, but this was fixed in https://github.com/ethereum/meteor-package-tools/commit/f3c9a0c0f084ef22543068f460282254a3bd6a7c . I don't understand what's gone on here...

**Comment by derron** [comment]
@area I have seen the commit https://github.com/ethereum/meteor-package-tools/commit/f3c9a0c0f084ef22543068f460282254a3bd6a7c, but this commit only fix the first url with space, the second one isn't fixed, so I fix it in my commit.

**Comment by area** [comment]
Yup, I'm an idiot. Thanks for pointing out the obvious!

**Comment by derron** [comment]
@area, When will this commit be merged?

**Comment by area** [comment]
I'm not a developer on this package, just a user of it who ran across the same issue.

**Comment by alexvandesande** [comment]
thanks for the PR!

**Pull request merged**
